### ISSUE TITLE
Minor typos (3) in test.js

### ISSUE THREAD

**Issue by LibraSun** [toggledbits/lexpjs#6]
, { expr: "[1,2,3]", Xxpect: [1,2,3] }
    , { expr: "{ alpha: 1, beta: 2, gamma: 3 }", Xxpect: { alpha: 1, beta: 2, gamma: 3 } }
    , { expr: "{ 'first': 'a', ['strange id']: 'b', 'Another Strange ID': 'voodoo' }", Xxpect: {} }

Keys should read "expect:" not "Xxpect:"

**Comment by toggledbits** [comment]
Intentional. It's a form of placeholder. The current test script cannot perform a comparison between anything other than primitive objects; it can't compare two objects or two arrays to see if they are equal, or equivalent. So those require manual review to determine correctness at the moment, and the misspelled key is my reminder that I need to enhance that some day.
